version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-eks: circleci/aws-eks@2.2.0
  aws-ecr: orbies/aws-ecr@1.2.1
  helm: circleci/helm@2.0.1

jobs:
  deploy:
    executor: aws-cli/default
    environment:
      EKS_CLUSTER_NAME: eks-dev-cluster
      EKS_CLUSTER_REGION: ap-south-1
      ECR_REPO_NAME: circle-ci-test
      ECR_REPO_REGION: ap-south-1
      HELM_APP_NAME: sample-nginx-app
      HELM_APP_DIR: sample-nginx-app
      HELM_APP_NAMESPACE: default
    steps:
      - checkout
      - helm/install-helm-client
      - setup_remote_docker:
          version: 20.10.11
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          command: export AWS_ECR_REGISTRY_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: $EKS_CLUSTER_NAME
          aws-region: $EKS_CLUSTER_REGION
          install-kubectl: true
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          # push-image: true
          region: ECR_REPO_REGION
          # registry-id: AWS_ECR_REGISTRY_ID
          repo: ECR_REPO_NAME
          tag: latest,$CIRCLE_SHA1
      - run:
          command: |
            kubectl get services
          name: Test cluster
      - run:
          name: Test Helm
          command: |
            helm upgrade -i $HELM_APP_NAME $HELM_APP_DIR -n $HELM_APP_NAMESPACE 
      - run:
          command: aws s3 ls
          name: aws s3 ls
      - run:
          command: env
          name: envs
workflows:
  main:
    jobs:
      - deploy:
          context: aws-credentials-context