version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  # helm: circleci/helm@1.1.2

jobs:
  deploy:
    executor: aws-cli/default

    steps:
      - checkout

      # Build and test your application here

      # Authenticate with EKS
      # - aws-eks/eks-authenticate:
      #     cluster-name: eks-dev-cluster
      #     region: ap-south-1

      # Install Helm and deploy the application
      # - helm/install-helm
      # - helm/upgrade-chart:
      #     chart: my-helm-chart
      #     release-name: my-release-name
      #     namespace: my-namespace
      #     values: |
      #       image:
      #         tag: $CIRCLE_SHA1
      #       service:
      #         type: LoadBalancer
      #       replicas: 3
      - run:
          command: aws s3 ls
          name: aws s3 ls
workflows:
  main:
    jobs:
      - deploy:
          context: aws-credentials-context