version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-eks: circleci/aws-eks@2.2.0
  aws-ecr: circleci/aws-ecr@8.2.1
  helm: circleci/helm@2.0.1

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - helm/install-helm-client
      - setup_remote_docker:
          version: 20.10.11
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: eks-dev-cluster
          aws-region: ap-south-1
          install-kubectl: true
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          push-image: true
          region: ap-south-1
          registry-id: AWS_ECR_REGISTRY_ID
          repo: circle-ci-test
          tag: latest,$CIRCLE_SHA1
      - run:
          command: |
            kubectl get services
          name: Test cluster
      - run:
          command: |
            helm ls
          name: Test Helm
      - run:
          command: aws s3 ls
          name: aws s3 ls
      - run:
          command: env
          name: envs
workflows:
  main:
    jobs:
      - deploy:
          context: aws-credentials-context
