apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi_volume.secretProviderClassName }}
spec:
  provider: aws   
  secretObjects:
  {{- range .Values.secret_env }}
  - secretName: application-secret-{{ lower .aws_secret }}
    type: Opaque
    data:
    - objectName: {{ .aws_secret }}
      key: {{ .aws_secret }}
  {{- end }}
  parameters:
    region: {{ .Values.secret_region }}
    objects: |
      {{- range .Values.secret_env }}
        - objectName: {{ .aws_secret }}  # the AWS secret
          objectType: "secretsmanager"
      {{- end }}