name: EKS-DEPLOY-STAGE
on:
  workflow_dispatch:
    inputs:
      EKS_CLUSTER_NAME:
        description: "EKS Cluster Name"
        default: "eks-dev-cluster"
      EKS_CLUSTER_REGION:
        description: "EKS Cluster Region"
        default: "ap-south-1"
      HELM_APP_NAME:
        description: "Application Name"
      HELM_APP_DIR:
        description: "Application Helm Chart Directory"
      HELM_APP_NAMESPACE:
        description: "Helm chart installation NameSpace"
env:
  ROLE_ARN: arn:aws:iam::192182953222:role/EKSFullAccess

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.EKS_CLUSTER_REGION }}
        role-to-assume: ${{ env.ROLE_ARN }}
        role-duration-seconds: 900
        role-session-name: DeployStageSession
    - name: Assume Role Check
      run: aws sts get-caller-identity
    - name: Update kubeconfig file
      id: Update-KubeConfig
      run: echo aws eks update-kubeconfig --region ${{ github.event.inputs.EKS_CLUSTER_REGION }} --name ${{ github.event.inputs.EKS_CLUSTER_NAME }}
#     - name: check pods in namespace
#       id: Check-Pods-Before-Upgrade
#       run: kubectl get pods -n $HELM_APP_NAMESPACE
#     - name: Helm Upgrade
#       run: helm upgrade -i $HELM_APP_NAME $HELM_APP_DIR -n $HELM_APP_NAMESPACE
    - name: check pods in namespace
      id: Check-Pods-Before-Upgrade
      run: echo ${{ github.event.inputs.HELM_APP_NAMESPACE }}
    - name: Helm Upgrade
      run: echo ${{ github.event.inputs.HELM_APP_NAME }} ${{ github.event.inputs.HELM_APP_DIR }} ${{ github.event.inputs.HELM_APP_NAMESPACE }}
