name: EKS-DEPLOY-STAGE
on:
  workflow_dispatch:
    inputs:
      EKS_CLUSTER_NAME:
        description: "EKS Cluster Name"
        default: "eks-dev-cluster"
        required: true
      EKS_CLUSTER_REGION:
        description: "EKS Cluster Region"
        default: "ap-south-1"
        required: true
      HELM_APP_NAME:
        description: "Application Name"
        required: true
      HELM_APP_DIR:
        description: "Application Helm Chart Directory"
        required: true
      HELM_APP_NAMESPACE:
        description: "Helm chart installation NameSpace"
        required: true
      IMAGE_TAG:
        description: "Set Image Tag for Web Worker PDF"
        required: true
env:
  EKS_CLUSTER_NAME: ${{ github.event.inputs.EKS_CLUSTER_NAME }}
  EKS_CLUSTER_REGION: ${{ github.event.inputs.EKS_CLUSTER_REGION }}
  HELM_APP_NAME: ${{ github.event.inputs.HELM_APP_NAME }}
  HELM_APP_DIR: ${{ github.event.inputs.HELM_APP_DIR }}
  HELM_APP_NAMESPACE: ${{ github.event.inputs.HELM_APP_NAMESPACE }}
  IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG }}
  ROLE_ARN: arn:aws:iam::192182953222:role/EKSFullAccess

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.EKS_CLUSTER_REGION }}
        role-to-assume: ${{ env.ROLE_ARN }}
        role-duration-seconds: 900
        role-session-name: DeployStageSession
    - name: Assume Role Check
      run: aws sts get-caller-identity
    - name: Update kubeconfig file
      id: Update-KubeConfig
      run: aws eks update-kubeconfig --region $EKS_CLUSTER_REGION --name $EKS_CLUSTER_NAME
    - name: check pods in namespace
      id: Check-Pods-Before-Upgrade
      run: kubectl get pods -n $HELM_APP_NAMESPACE
    - name: Helm Upgrade
      run: helm upgrade -i $HELM_APP_NAME $HELM_APP_DIR -n $HELM_APP_NAMESPACE --set web_image.tag=$IMAGE_TAG --set worker_image.tag=$IMAGE_TAG --set pdf_image.tag=$IMAGE_TAG
